version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - API_HOST=${API_HOST}
    - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    - BUCKET_NAME=${BUCKET_NAME}
    - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
    - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    ports:
    - 8080:8080
    depends_on:
    - db
    command: [gunicorn]

  db:
    image: postgres:14
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
